---
name: Pre-build dev container

on: [push, workflow_dispatch]

jobs:
  build:
    name: Pre-build dev container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build and push image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          imageTag: latest,v1.5.1
          platform: linux/amd64,linux/arm64
          push: always
